use java_brains;


CREATE TABLE JB_TM_MONITOR_CONFIG (
JOB_ID VARCHAR(100) NOT NULL,
START_TIME INT NOT NULL,
END_TIME INT NOT NULL,
JOB_STATUS VARCHAR(1) NOT NULL,
JOB_DESC VARCHAR(100) NOT NULL,
RUN_STATUS VARCHAR(1) NOT NULL,
THREAD_CNT INT NOT NULL
);

insert into JB_TM_MONITOR_CONFIG (JOB_ID,START_TIME,END_TIME,JOB_STATUS,JOB_DESC,RUN_STATUS,THREAD_CNT) values('GiRecvTask',9,18,'Y','GiRecvTask','N',1);
insert into JB_TM_MONITOR_CONFIG (JOB_ID,START_TIME,END_TIME,JOB_STATUS,JOB_DESC,RUN_STATUS,THREAD_CNT) values('GiScrubTask',9,18,'Y','GiScrubTask','N',1);
insert into JB_TM_MONITOR_CONFIG (JOB_ID,START_TIME,END_TIME,JOB_STATUS,JOB_DESC,RUN_STATUS,THREAD_CNT) values('GiSendTask',9,18,'Y','GiSendTask','N',1);
insert into JB_TM_MONITOR_CONFIG (JOB_ID,START_TIME,END_TIME,JOB_STATUS,JOB_DESC,RUN_STATUS,THREAD_CNT) values('GiSynchTask',9,18,'Y','GiSynchTask','N',1);
insert into JB_TM_MONITOR_CONFIG (JOB_ID,START_TIME,END_TIME,JOB_STATUS,JOB_DESC,RUN_STATUS,THREAD_CNT) values('NPCIServcTask',9,18,'Y','NPCIServcTask','N',1);
select * from JB_TM_MONITOR_CONFIG;

